.MODEL SMALL
.STACK 100H

.DATA
LF EQU 0AH
CR EQU 0DH
MSG DB 'PLEASE ENTER A NUMBER: $' ;PROPMT MESSAGE
RESULT DB 'RESULT (X-2Y): $'
X DB ?                          ;NEED THREE VARIABLE TO CALCULATE
Y DB ?
Z DB ?

.CODE
;MAIN PROCEDURE
MAIN PROC
    ;INITIALIZE DATA TO DS REGISTER
    MOV AX, @DATA
    MOV DS, AX

    ;PRINT THE PROMPT MESSAGE
    MOV DX, OFFSET MSG
    MOV AH, 9
    INT 21H

    ;TAKE THE INPUT X
    MOV AH, 1
    INT 21H
    SUB AL, '0'
    MOV X, AL

    ;PRINT THE NEW LINE
    MOV DL, LF
    MOV AH, 2
    INT 21H
    MOV DL, CR
    INT 21H

    ;PRINT THE PROMPT MESSAGE
    MOV DX, OFFSET MSG
    MOV AH, 9
    INT 21H

    ;TAKE THE INPUT X
    MOV AH, 1
    INT 21H
    SUB AL, '0'
    MOV Y, AL

    ;CALCULATE Z
    ADD AL, X   ;IN AL THERE IS X+Y
    MOV BL, 25  ;STORE 25 IN BL
    SUB BL, AL  ;SUBTRUCT X+Y FROM 25 AND STORE THE VALUE IN BL
    ADD BL, '0'  ;CONVERT THE VALUE IN ASCII NUMBER
    MOV Z, BL   ;STORE THE VALUE OF BL IN Z

    ;PRINT NEW LINE
    MOV DL, LF
    MOV AH, 2
    INT 21H
    MOV DL, CR
    INT 21H

    ;PRINT PROMPT MESSAGE
    MOV DX, OFFSET RESULT
    MOV AH, 9
    INT 21H

    ;PRINT Z
    MOV DL, Z
    MOV AH, 2
    INT 21H

    ;RETURN CONTROL TO DOS
    MOV AH, 4CH
    INT 21H
MAIN ENDP
END MAIN